apiVersion: v1
kind: Pod
metadata:
 name: advn

spec:
 containers:
 - name: flaskapp
   image: bakhtawar375/adventure
   env:
    - name: MYSQL_HOST
      value: "database"      # This Is Your MYSQL Service Name Or IP
    - name: MYSQL_USER
      value: "root"
    - name: MYSQL_PASSWORD
      value: "kali"
    - name: MYSQL_DB
      value: "shoot"
 ports:
  - containerPort: 5000
 imagePullPolicy: Always
